### ISSUE TITLE
`docstring_style = numpy` breaks in a strange way

### ISSUE THREAD

**Issue by sobolevn** [terrencepreilly/darglint#133]
It fails with: 

```
./wemake_python_styleguide/visitors/ast/complexity/access.py

  1:1      DAR000: Unexpected exception in darglint: Unsupported section type, Sections.VARIABLES_SECTION
  import ast
  ^

Full list of violations and explanations:
https://wemake-python-stylegui.de/en/0.14.1/pages/usage/violations/
Makefile:5: recipe for target 'lint' failed
make: *** [lint] Error 1
Error: The operation was canceled.
```

Build: https://github.com/wemake-services/wemake-python-styleguide/pull/1671/checks?check_run_id=1253881873

**Comment by terrencepreilly** [comment]
I'm not able to reproduce this.  Could you give me what version of `darglint` you're running, and a link to the file you're running against?

**Comment by sobolevn** [comment]
Yes, sure! `1.5.5`, link: https://github.com/wemake-services/wemake-python-styleguide/runs/1269495969#step:6:38
It is the latest version at the moment.

I can also reproduce this failure locally:
<img width="752" alt="Снимок экрана 2020-10-18 в 0 43 26" src="https://user-images.githubusercontent.com/4660275/96354073-f8eb0980-10da-11eb-8d3f-d605470fa6c5.png">

**Comment by skarzi** [comment]
I'm not 100% sure what exactly `Sections.VARIABLES_SECTION`  represents, but it seems that `numpy` style docstring doesn't support it - https://numpydoc.readthedocs.io/en/latest/format.html#sections - so maybe the solution will be to exclude it in [`satisfies_strictness` method](https://github.com/terrencepreilly/darglint/blob/master/darglint/docstring/numpy.py#L354) implementation like it's done in [`docstrings.google`](https://github.com/terrencepreilly/darglint/blob/6bc5d764db86626a996de1ff50925f976bf1449e/darglint/docstring/google.py#L418)?

I will be more than happy to prepare PR if you think it can be a potential solution :smile:

**Comment by sobolevn** [comment]
Fixed!

Proof: https://github.com/wemake-services/wemake-python-styleguide/pull/1671
