### ISSUE TITLE
Option to ignore common exceptions in raises

### ISSUE THREAD

**Issue by vnmabus** [terrencepreilly/darglint#144]
Exceptions such as `ValueError`, `TypeError` or `NotImplemented` are common in some codebases, and requiring their presence in the `Raises` section can be a burden. Could it be possible to configure a set of "ignorable" non-required exceptions in the setup.cfg?

**Comment by terrencepreilly** [comment]
That seems reasonable.  I'm working on some performance issues, and on supporting numpy docstrings better.  I'll come back to this once I've addressed those issues, if nobody has implemented it.

**Comment by palt0** [comment]
Hello, if no one is already working on this, I'd very much like to implement it!

**Comment by terrencepreilly** [comment]
Sure, feel free: nobody's working on this that I know of.  I have no particular preference for the parameter name.  Thanks!

**Comment by maltevesper** [comment]
@terrencepreilly I believe this can be closed thanks to @palt0 's patch?
