### ISSUE TITLE
Add an option to support printing explanation of error code

### ISSUE THREAD

**Issue by dclong** [terrencepreilly/darglint#145]
The error message is too short and might be confusing for users who are not very familiar with the error codes. Printing explanation of error code helps.

**Comment by terrencepreilly** [comment]
The README gives instructions on setting the [verbosity of error codes](https://github.com/terrencepreilly/darglint#command-line-use) (`darglint -v 2`).  It also explains how to format custom error messages (`darglint --message-template ...`).  And there is an option to list all errors, with explanations (`darglint --list-errors`.)  I think there are plenty of options for anyone looking for more information.
