### ISSUE TITLE
0.5.3 release?

### ISSUE THREAD

**Issue by raddessi** [terrencepreilly/darglint#15]
Hi! I was just wondering if you are planning a 0.5.3 release soon. If not, can I request one from the current master? Just so pip sees all the latest changes :) Thanks!

**Comment by terrencepreilly** [comment]
Oops, sorry!  Last time I tried to upload it, pypi was down for maintenance.  I forgot to try again after that.  It should be up to date (0.5.3), now.

The next update probably won't come for a month or so -- I just got a new job and I'm going to be moving across the country.  If there's anything small, though, I should be able to tackle it pretty easily.
