### ISSUE TITLE
Just to say great job

### ISSUE THREAD

**Issue by JPFrancoia** [terrencepreilly/darglint#17]
Just a small message to say your tool is a really good idea. I wasn't able to find anything like it and I think it's essential. Keep up the good work! I hope you're still working on it.

**Comment by terrencepreilly** [comment]
Thank you!  Yes, I'm still working on it, albeit slowly.  I've run into a bit of a rabbit hole trying rewrite the parser, but it'll get done soon, I hope.

**Comment by rpkilby** [comment]
btw - also want to express my gratitude. The flake8 integration has been incredibly helpful. 

👍

**Comment by adithyabsk** [comment]
This is great, I thought I would add a note as well. Will be very helpful.
