### ISSUE TITLE
typing.Deque only exists on python 3.6.1 and later

### ISSUE THREAD

**Issue by rpkilby** [terrencepreilly/darglint#2]
The `tox.ini` indicates that this package is tested against python 3.4, 3.5, and 3.6, however `typing.Deque` was only added in 3.6.1, so its import breaks these older versions.

**Comment by rpkilby** [comment]
On a related note, it might be beneficial to add a CI provider to the project (eg, Travis CI). It would help guard against this kind of issue.

**Comment by terrencepreilly** [comment]
Ah, you're right.  Thanks for catching this.

**Comment by terrencepreilly** [comment]
Resolved for version 0.3.4.
