### ISSUE TITLE
Missing release tags

### ISSUE THREAD

**Issue by rpkilby** [terrencepreilly/darglint#3]
Looking through the git history, there are a few versions that are missing tags. Namely, `0.2.0` and later. Additionally, there are a few missing releases on PyPI (`0.1.0`, `0.2.0`, and `0.3.1`).

**Comment by terrencepreilly** [comment]
You're right.  I forgot to add tags while I was re-writing the parser.  They should be up-to-date now.  It looks like a couple of them don't correspond exactly to the version in the setup.py file.  I believe I probably updated the setup.py version just before pushing to pypi.  I'll have to make a hook or something to not forget in the future.
