### ISSUE TITLE
__init__: 'Raise' object has no attribute 'ecx'

### ISSUE THREAD

**Issue by adithyabsk** [terrencepreilly/darglint#34]
I seem to be getting this weird exception that I've isolated to darglint, it doesn't cause any issues but thought I'd bring it up in case it was. 
flake8 throws:
`__init__: 'Raise' object has no attribute 'ecx'`

When I run flake8 with the highest verbosity, I am still unable to trace the error.

Here is a minimum example that raises the error:
```python
class NewException(Exception):
    pass

def wrapper():
    class SomeClass():
        def __init__(self, *args, **kwargs):
            try:
                raise NewException
            except Exception as e:
                raise type(e)(
                    str(e) + " Custom Message"
                )
    return SomeClass
```

**Comment by rpkilby** [comment]
I assume it's this line, and that it should probably be `exc`.

https://github.com/terrencepreilly/darglint/blob/0c46112520aaffa454c756c116e048b8e6b7adb1/darglint/function_description.py#L210

**Comment by terrencepreilly** [comment]
Good catch.  Out of curiosity, why are you catching an exception class and raising an instantiated instance of it?

Thanks, @rpkilby, that was exactly it.

Resoved in 0.5.8

**Comment by adithyabsk** [comment]
@terrencepreilly Not sure if there is a better way of doing this, but the idea was the keep the same instance type that was captured (likely a subclass) and re-raise with some additional context. If there is a better way of doing that, let me know!
