### ISSUE TITLE
`darglint` overlaps with `flake8-pep3101` in some error codes

### ISSUE THREAD

**Issue by sobolevn** [terrencepreilly/darglint#40]
`darglint` overlaps with `flake8-pep3101` in some error codes: https://github.com/gforcada/flake8-pep3101

```
S001: Describes that something went wrong in parsing the docstring.
S002: An argument/exception lacks a description.
```

I suggest to use `DAL`, `ARG`, or any other three letter codes for issues. `flake8` supports it and the overlap chance is minimal.

**Comment by peterjc** [comment]
Also flake8 recommends three letter prefixes since v3 to reduce the chance of these clashes.

**Comment by terrencepreilly** [comment]
Yeah, I figured that this would happen at some point.  I'll switch it to `DAR`.  peterjc@, do you know where it says that?  It would be nice to see if they have a list of codes which are taken so far.  (The only documentation I've been able to find said, "Each code consists of an upper case ASCII letter followed by three digits", so that's probably outdated.)

**Comment by peterjc** [comment]
The official documentation is a tiny bit at the end of this page:

http://flake8.pycqa.org/en/latest/plugin-development/registering-plugins.html

> **Flake8** requires each entry point to be unique amongst all plugins installed in the users environment. Selecting an entry point that is already used can cause plugins to be deactivated without warning!
>
> **Please Note:** Your entry point does not need to be exactly 4 characters as of Flake8 3.0. _Consider using an entry point with 3 letters followed by 3 numbers_ (i.e. ``ABC123`` ).

For more background, and a partial list of prefixes, see https://gitlab.com/pycqa/flake8/issues/339

**Comment by terrencepreilly** [comment]
Resolved in 9018557d745f9bdae12c7534129e47baf8f7d4d7.  Will close once the stable version 1.0.0 is published.

**Comment by sobolevn** [comment]
Hi, thanks a lot! Do you have any estimates about the release date of `1.0`?

**Comment by terrencepreilly** [comment]
I was working on getting conformance tests for flake8, but got stuck on a bug in flake8 itself (I think.)  I'll push it up this week.  In the meantime, 1,0.0-alpha is up to test, if you want.

**Comment by sobolevn** [comment]
@terrencepreilly do you need some help with the `flake8`-based tests? I have some experience in it.

**Comment by terrencepreilly** [comment]
Thanks, I think I've narrowed it down, though.
