### ISSUE TITLE
Parses normal comments in examples as noqa statements

### ISSUE THREAD

**Issue by Anderssorby** [terrencepreilly/darglint#45]
I have example code in my docstring like:
` >>> gpu = '0'  # The 0th GPU`

 This produces this error:
`S001: s Failed to parse noqa statement. Expected "# noqa" but received "# The"
`
Quick fix: add # noqa: S001 to the docstring.

However darglint should not treat these inline comments as noqa statements.

**Comment by terrencepreilly** [comment]
Good catch.  This should be resolved with the new parser, which I plan on releasing this coming week.

**Comment by terrencepreilly** [comment]
Resolved in 12fd2626bd120c6537634645d764d3284d003f01.  I'll close this issue once a non-alpha version is uploaded to pypi.
