### ISSUE TITLE
encoding error on windows

### ISSUE THREAD

**Issue by Trim21** [terrencepreilly/darglint#46]
My source file are `utf-8` encoded, and I'm using this tool on windows, but I got `'gbk' codec can't decode byte 0x80 in position 608: illegal multibyte sequence`.

consider adding `chardet` support?

**Comment by terrencepreilly** [comment]
Ah, good catch.  I'll just read the source files in as binary data and pass that to the ast module; it reads UTF-8 (or Latin1 or ASCII) fine then.

Resolved in 41f4f7081b852bd062f1d6576702934d43375753.  I'll close this issue once I push up a release with the fix.

**Comment by Trim21** [comment]
thanks for your work




------------------ Original ------------------
