### ISSUE TITLE
Add a new error to enforce having the type of parameters specified in the Docstring

### ISSUE THREAD

**Issue by FlorisHoogenboom** [terrencepreilly/darglint#49]
First of all thank you for the great package. I would like to make a proposal for another validation that checks whether the docstring specifies the type for each parameter. This in addition to `DAR203` which already checks that if type hints are used that the docstrings parameter types and the type hints match up. This new error would check for the specification of parameter types even in the absence of type hints.

Personally this would help my projects a lot since we don't use type hints in our function defintions, but we do want to enforce that types are documented in the docstring. I've taken the liberty to open #48 for this introducing `DAR104` which reads `The docstring parameter has no type specified` that may hopefully be a start for a discussion.

**Comment by terrencepreilly** [comment]
This seems like a good idea, but I wouldn't want this error reported by default.  (Most people, I think, don't use type annotations in docstrings.)  Before I merge this into master, I'll add a configuration option and flag to enable disabled-by-default errors. (This would be disabled by default.)  That way you could just add something like `enable=DAR104` to the configuration file to enable this on a per-project basis.

**Comment by FlorisHoogenboom** [comment]
I do agree indeed that this might be a validation that not everybody will use. How do you see the `enable` configuration option? If given than only the exceptions specified there are used? I think if we would only list by default disabled exceptions there things might become a bit complicated for end users especially with the `ignore` flag. If I can be of any help implementing that `enable` configuration option, I'm happy to help!

**Comment by terrencepreilly** [comment]
Most users that I've spoken with don't specify types in their docstrings. (They use type annotations, or don't specify them at all.)  So, hiding `DAR104`, from that perspective, simplifies things for most users.

For users who do want to document types, yes it will be more complicated.  However, having disabled-by-default linting is not unprecedented. [Flake8](https://flake8.pycqa.org/en/latest/user/options.html#cmdoption-flake8-enable-extensions) allows disabled-by-default extensions.  I hope to copy Flake8's design in this regard as much as possible to reduce the cognitive burden of the feature.

In terms of design philosophy, darglint is not an opinionated tool.  Generally, darglint tries to raise errors only when a user tries (and fails) to document something.  So, we could probably enable this feature if a user attempts to specify the type of anything in the docstring. That is, if a user specifies the type of one parameter they should specify the types of all the parameters.

**Comment by FlorisHoogenboom** [comment]
Solved by #48
