### ISSUE TITLE
Add flake8 plugin?

### ISSUE THREAD

**Issue by rpkilby** [terrencepreilly/darglint#6]
Have you considered adding a [flake8](http://flake8.pycqa.org/en/latest/) extension? If you're not aware, flake8 is a general framework for executing all sorts of style checks. 

An example of a similar plugin would be [`flake8-docstrings`](https://github.com/PyCQA/flake8-docstrings), which integrates [`pycodestyle`](https://github.com/PyCQA/pydocstyle) with `flake8`. 

As an added benefit, this plugin would indirectly solve the exitcode handling issue, as well as handling file inputs (eg, no longer necessary to use xargs to feed multiple packages to `darglint`.

**Comment by terrencepreilly** [comment]
I wasn't aware of this.  It sounds like a great idea, especially since it would make an easy means of integrating with IDEs, etc.  I'll look into it.

**Comment by terrencepreilly** [comment]
I've added the flake8 extension.  I haven't exposed all of the command line arguments through flake8, but will get to it eventually.  For now, configuration can be done through the normal configuration files.
Thanks @rpkilby for the suggestion!

Resolved for version 0.5.0
