### ISSUE TITLE
Cannot handle newline after Google-style argument name

### ISSUE THREAD

**Issue by languitar** [terrencepreilly/darglint#66]
While not explicitly stated in the Google style guide, the following way of formatting argument descriptions works with all tools I have tested:
```
    Args:
        foo:
            Description text
```
However, darglint complains with a DAR101 about a missing parameter documentation.

**Comment by terrencepreilly** [comment]
You're right, I just need to add a rule in the parser for that.  I'll mark it as a bug so that I don't forget.  Thanks!

**Comment by terrencepreilly** [comment]
Although we fixed this for arguments, it also appears to be happening for the raises section.  I'll leave it open until that's resolved as well.

**Comment by terrencepreilly** [comment]
Resolved in v1.2.4.
