### ISSUE TITLE
Setup a CI

### ISSUE THREAD

**Issue by sobolevn** [terrencepreilly/darglint#72]
Hi, @terrencepreilly! Thanks a lot for your hard work on this project!

I would like to propose adding a CI for this project.
Since it is using `tox` it should be pretty easy to do.
Here's an example for `travis` and `tox`: https://github.com/PyCQA/pep8-naming/blob/master/.travis.yml

Related: https://github.com/wemake-services/wemake-python-styleguide/issues/1138

**Comment by terrencepreilly** [comment]
That seems like a good idea.  I'll try to get around to it sometime this week or next.

**Comment by terrencepreilly** [comment]
Thanks for the reminder -- I've been meaning to get to this for a while.  Running the pre-commits is going to be a good deal more work, but this is pretty good for now.

Resolved in 0d55aa63c262650a62a71747565ad74af60a053e.
