### ISSUE TITLE
DAR401 on bare raise

### ISSUE THREAD

**Issue by Dreamsorcerer** [terrencepreilly/darglint#82]
I get a DAR401 on a bare raise statement.

Given this means it's reraising an existing exception from other code, I'm not sure it makes sense for this violation (the exception would still occur if there was no try block, and it wouldn't give a violation in that case).

**Comment by terrencepreilly** [comment]
Yes, this is addressed in Issue #68.  I'll close this in favor of that issue.  Thanks!

**Comment by Dreamsorcerer** [comment]
I think that's actually the opposite of my suggestion, but if that's the intended behaviour, so be it.
