### ISSUE TITLE
Handle multiple Exceptions in except clause followed by re-raise

### ISSUE THREAD

**Issue by adithyabsk** [terrencepreilly/darglint#84]
## Situation
Here is a reproducible bug.

```python
# scratch_3.py

class CustomError(Exception):
    """Some custom error."""

    pass

def test():
    """Test function.

    Returns:
        0

    Raises:
        CustomError: some more descriptive error

    """
    try:
        pass
    except (ValueError, TypeError):
        raise CustomError("More descriptive message")

    return 0

```
```console
$ darglint scratch_3.py
```

## Expectation
No error

## Result
`'Tuple' object has no attribute 'id'`

**Comment by terrencepreilly** [comment]
I wasn't able to reproduce this with version 1.2.2.  Which version are you running?

**Comment by adithyabsk** [comment]
Oh I see 1.2.2 is released to pypi but not tagged on GitHub, didn't realize there was a newer version. Let me check

**Comment by adithyabsk** [comment]
@terrencepreilly yep, you're right. The error does not exist in the latest version.
