### ISSUE TITLE
DAR101: Ignore arguments marked as unused

### ISSUE THREAD

**Issue by Dreamsorcerer** [terrencepreilly/darglint#92]
Arguments prefixed with an underscore should not be required to appear in the docstring.

This change was also made recently to pydocstyle, so it would also help ensure consistency between darglint and pydocstyle: https://github.com/PyCQA/pydocstyle/issues/438

**Comment by terrencepreilly** [comment]
That seems like a good idea.  I'll change it so that darglint doesn't require that argument. (But if that argument is present in the docstring, it'll still run other checks on it.)

**Comment by terrencepreilly** [comment]
This will be enabled when v1.4.0 is released.  Thanks for the suggestion!
