### ISSUE TITLE
Support for multiple exceptions in except clause.

### ISSUE THREAD

**Issue by kozako2** [terrencepreilly/darglint#99]
Code:
```python
try:
    pass
except (KeyError, IOException):
    pass
```
Is causing `ERROR:darglint:While getting ast.Attribute representation a node had an unexpected type Tuple`  (https://github.com/terrencepreilly/darglint/blob/master/darglint/analysis/raise_visitor.py#L52)

is this expected behaviour? 

Thanks in advance.

**Comment by terrencepreilly** [comment]
This is a duplicate of Issue #97.  It will be resolved in v1.4.1.
